#!/usr/bin/env sh
sed -i "s|PHP_FPM_ERROR_LOG|$PHP_FPM_ERROR_LOG|g" "$PHP_FPM_APP_CONF_FILE"
sed -i "s|NGINX_RUN_USER|$NGINX_RUN_USER|g" "$PHP_FPM_APP_CONF_FILE"
sed -i "s|NGINX_RUN_GROUP|$NGINX_RUN_GROUP|g" "$PHP_FPM_APP_CONF_FILE"
