name: Build ghcr.io/unb-libraries/nginx-php

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  deploy:
    uses: unb-libraries/dockworker-baseimage/.github/workflows/build-base-image.yaml@6.x
    with:
      image-name: ghcr.io/unb-libraries/nginx-php
      protected-tags: '3.x,2.x,1.x-7.x,1.x-7.x-composer2,1.x-7.3'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
      GH_CONTAINER_REGISTRY_USER: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
